// Generated by gencpp from file serial_manager/distance_msg.msg
// DO NOT EDIT!


#ifndef SERIAL_MANAGER_MESSAGE_DISTANCE_MSG_H
#define SERIAL_MANAGER_MESSAGE_DISTANCE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace serial_manager
{
template <class ContainerAllocator>
struct distance_msg_
{
  typedef distance_msg_<ContainerAllocator> Type;

  distance_msg_()
    : header()
    , grafic()  {
      grafic.assign(0.0);
  }
  distance_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , grafic()  {
  (void)_alloc;
      grafic.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 57>  _grafic_type;
  _grafic_type grafic;





  typedef boost::shared_ptr< ::serial_manager::distance_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_manager::distance_msg_<ContainerAllocator> const> ConstPtr;

}; // struct distance_msg_

typedef ::serial_manager::distance_msg_<std::allocator<void> > distance_msg;

typedef boost::shared_ptr< ::serial_manager::distance_msg > distance_msgPtr;
typedef boost::shared_ptr< ::serial_manager::distance_msg const> distance_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_manager::distance_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_manager::distance_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'serial_manager': ['/home/robot/charlie_ws/src/SerialManager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_manager::distance_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_manager::distance_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_manager::distance_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_manager::distance_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_manager::distance_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_manager::distance_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_manager::distance_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8328157916dc7d8e983a8a56463b89a";
  }

  static const char* value(const ::serial_manager::distance_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8328157916dc7d8ULL;
  static const uint64_t static_value2 = 0xe983a8a56463b89aULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_manager::distance_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_manager/distance_msg";
  }

  static const char* value(const ::serial_manager::distance_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_manager::distance_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[57] grafic\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::serial_manager::distance_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_manager::distance_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.grafic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distance_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_manager::distance_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_manager::distance_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "grafic[]" << std::endl;
    for (size_t i = 0; i < v.grafic.size(); ++i)
    {
      s << indent << "  grafic[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.grafic[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MANAGER_MESSAGE_DISTANCE_MSG_H
