// Generated by gencpp from file pozyx_ros/EulerAngles.msg
// DO NOT EDIT!


#ifndef POZYX_ROS_MESSAGE_EULERANGLES_H
#define POZYX_ROS_MESSAGE_EULERANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pozyx_ros
{
template <class ContainerAllocator>
struct EulerAngles_
{
  typedef EulerAngles_<ContainerAllocator> Type;

  EulerAngles_()
    : yaw(0.0)
    , roll(0.0)
    , pitch(0.0)  {
    }
  EulerAngles_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::pozyx_ros::EulerAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pozyx_ros::EulerAngles_<ContainerAllocator> const> ConstPtr;

}; // struct EulerAngles_

typedef ::pozyx_ros::EulerAngles_<std::allocator<void> > EulerAngles;

typedef boost::shared_ptr< ::pozyx_ros::EulerAngles > EulerAnglesPtr;
typedef boost::shared_ptr< ::pozyx_ros::EulerAngles const> EulerAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pozyx_ros::EulerAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pozyx_ros::EulerAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pozyx_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pozyx_ros': ['/home/robot/charlie_ws/src/pozyx_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pozyx_ros::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pozyx_ros::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pozyx_ros::EulerAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a95abc59ede2a93c5088a3b41defbc41";
  }

  static const char* value(const ::pozyx_ros::EulerAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa95abc59ede2a93cULL;
  static const uint64_t static_value2 = 0x5088a3b41defbc41ULL;
};

template<class ContainerAllocator>
struct DataType< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pozyx_ros/EulerAngles";
  }

  static const char* value(const ::pozyx_ros::EulerAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n\
float32 roll\n\
float32 pitch\n\
";
  }

  static const char* value(const ::pozyx_ros::EulerAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pozyx_ros::EulerAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pozyx_ros::EulerAngles_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POZYX_ROS_MESSAGE_EULERANGLES_H
