camera:
  camera_nodelet_manager: {num_worker_threads: 4}
  depth:
    image:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_raw:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_rect:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_rect_raw:
      compressed: {format: jpeg, jpeg_quality: 100, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 63, target_bitrate: 800000}
  depth_rectify_depth: {interpolation: 0}
  depth_registered:
    sw_registered:
      image_rect:
        compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
        compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
        theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
      image_rect_raw:
        compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
        compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
        theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
  disparity_depth: {max_range: 4.0, min_range: 0.5}
  disparity_registered_sw: {max_range: 4.0, min_range: 0.5}
  driver: {
    base_frame_id: camera_link, 
    camera_type: R200, 
    color_backlight_compensation: 1,
    color_brightness: 56, 
    color_contrast: 32, 
    color_enable_auto_exposure: 1, 
    color_enable_auto_white_balance: 1,
    color_exposure: 1, 
    color_fps: 30, 
    color_frame_id: camera_rgb_frame, 
    color_gain: 32,
    color_gamma: 220, 
    color_height: 480, 
    color_hue: -655, 
    color_optical_frame_id: camera_rgb_optical_frame,
    color_saturation: 128, 
    color_sharpness: 0, 
    color_white_balance: 6500, 
    color_width: 640,
    depth_fps: 30, 
    depth_frame_id: camera_depth_frame, 
    depth_height: 360, 
    depth_optical_frame_id: camera_depth_optical_frame,
    depth_width: 480, 
    enable_color: true, 
    enable_depth: true, 
    enable_fisheye: false,
    enable_imu: false, 
    enable_ir: true, 
    enable_ir2: true, 
    enable_pointcloud: false,
    enable_tf: true, 
    ir2_frame_id: camera_ir2_frame,
     ir_frame_id: camera_ir_frame,
    mode: manual, 
    r200_auto_exposure_bottom_edge: 479, 
    r200_auto_exposure_left_edge: 639,
    r200_auto_exposure_right_edge: 639,
    r200_auto_exposure_top_edge: 479, 
    r200_dc_estimate_median_decrement: 5,
    r200_dc_estimate_median_increment: 5, 
    r200_dc_lr_threshold: 12, 
    r200_dc_median_threshold: 175,
    r200_dc_neighbor_threshold: 24, 
    r200_dc_preset: 4, 
    r200_dc_score_maximum_threshold: 430,
    r200_dc_score_minimum_threshold: 24, 
    r200_dc_second_peak_threshold: 47, 
    r200_dc_texture_count_threshold: 6,
    r200_dc_texture_difference_threshold: 48, 
    r200_emitter_enabled: 0, 
    r200_lr_auto_exposure_enabled: 0,
    r200_lr_exposure: 7, 
    r200_lr_gain: 100, 
    serial_no: '', 
    usb_port_id: ''}
  ir:
    image_raw:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_rect_ir:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
  ir2:
    image_raw:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
  ir_rectify_ir: {interpolation: 1}
  points_xyzrgb_sw_registered: {queue_size: 100}
  rgb:
    image_color:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_mono:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_raw:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_rect_color:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
    image_rect_mono:
      compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
      compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
      theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
  rgb_debayer: {debayer: 0}
  rgb_rectify_color: {interpolation: 1}
  rgb_rectify_mono: {interpolation: 1}
rosdistro: 'indigo

  '
roslaunch:
  uris: {host_cear01_dev__35180: 'http://cear01-dev:35180/'}
rosversion: '1.11.21

  '
run_id: 293fff90-6c7f-11e7-bfc1-f816548af1f1
